In [10]:
import pandas as pd

aerolines = pd.read_csv('train.csv')
display(aerolines)

# siendo "satisfaction" el objetivo
# me dice cuántos hay de cada tipo en dicha columna
class_distribution = aerolines["satisfaction"].value_counts()
print(class_distribution)

countNaN = aerolines.isna().sum()
print("=== countNaN ===")
print(countNaN)

# Se opta por borrar las filas que tengan uno o más datos con NaN
# Se pueden rellenar con la media o con la mediana
# Pero se ha decidido así pq hay 100.000 filas y solo 300 NaN
aerolines = aerolines.dropna(how='any')
countNaN = aerolines.isna().sum()
print("=== countNaN ===")
print(countNaN)

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103899,103899,94171,Female,disloyal Customer,23,Business travel,Eco,192,2,1,...,2,3,1,4,2,3,2,3,0.0,neutral or dissatisfied
103900,103900,73097,Male,Loyal Customer,49,Business travel,Business,2347,4,4,...,5,5,5,5,5,5,4,0,0.0,satisfied
103901,103901,68825,Male,disloyal Customer,30,Business travel,Business,1995,1,1,...,4,3,2,4,5,5,4,7,14.0,neutral or dissatisfied
103902,103902,54173,Female,disloyal Customer,22,Business travel,Eco,1000,1,1,...,1,4,5,1,5,4,1,0,0.0,neutral or dissatisfied
103903,103903,62567,Male,Loyal Customer,27,Business travel,Business,1723,1,3,...,1,1,1,4,4,3,1,0,0.0,neutral or dissatisfied

satisfaction
neutral or dissatisfied    58879
satisfied                  45025
Name: count, dtype: int64
=== countNaN ===
Unnamed: 0                             0
id                                     0
Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  2
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Inflight service                       0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             310
satisfaction                           0
dtype: int64
=== countNaN ===
Unnamed: 0                           0
id                                   0
Gender                               0
Customer Type                        0
Age                                  0
Type of Travel                       0
Class                                0
Flight Distance                      0
Inflight wifi service                0
Departure/Arrival time convenient    0
Ease of Online booking               0
Gate location                        0
Food and drink                       0
Online boarding                      0
Seat comfort                         0
Inflight entertainment               0
On-board service                     0
Leg room service                     0
Baggage handling                     0
Checkin service                      0
Inflight service                     0
Cleanliness                          0
Departure Delay in Minutes           0
Arrival Delay in Minutes             0
satisfaction                         0
dtype: int64

In [11]:
# Borra la columna "Unamed: 0" y "id"
aerolines = aerolines.drop("Unnamed: 0",axis=1)
aerolines = aerolines.drop("id",axis=1)
display(aerolines)

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,3,1,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,Male,disloyal Customer,25,Business travel,Business,235,3,2,3,3,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,Female,Loyal Customer,26,Business travel,Business,1142,2,2,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,Female,Loyal Customer,25,Business travel,Business,562,2,5,5,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,Male,Loyal Customer,61,Business travel,Business,214,3,3,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103899,Female,disloyal Customer,23,Business travel,Eco,192,2,1,2,3,...,2,3,1,4,2,3,2,3,0.0,neutral or dissatisfied
103900,Male,Loyal Customer,49,Business travel,Business,2347,4,4,4,4,...,5,5,5,5,5,5,4,0,0.0,satisfied
103901,Male,disloyal Customer,30,Business travel,Business,1995,1,1,1,3,...,4,3,2,4,5,5,4,7,14.0,neutral or dissatisfied
103902,Female,disloyal Customer,22,Business travel,Eco,1000,1,1,1,5,...,1,4,5,1,5,4,1,0,0.0,neutral or dissatisfied
103903,Male,Loyal Customer,27,Business travel,Business,1723,1,3,3,3,...,1,1,1,4,4,3,1,0,0.0,neutral or dissatisfied

ONE HOT ENCODING

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

Gender=aerolines["Gender"]
GenderOHE = encoder.fit_transform(Gender.to_numpy().reshape(-1, 1))
aerolines = aerolines.drop("Gender",axis=1)

CustomerType=aerolines["Customer Type"]
CustomerTypeOHE = encoder.fit_transform(CustomerType.to_numpy().reshape(-1, 1))
aerolines = aerolines.drop("Customer Type",axis=1)

TypeofTravel=aerolines["Type of Travel"]
TypeofTraveOHE = encoder.fit_transform(TypeofTravel.to_numpy().reshape(-1, 1))
aerolines = aerolines.drop("Type of Travel",axis=1)

Class=aerolines["Class"]
ClassOHE = encoder.fit_transform(Class.to_numpy().reshape(-1, 1))
aerolines = aerolines.drop("Class",axis=1)

display(aerolines)
print(GenderOHE) #tambien valdria labelEncoder.

,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,13,460,3,4,3,1,5,3,5,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,25,235,3,2,3,3,1,3,1,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,26,1142,2,2,2,2,5,5,5,5,4,3,4,4,4,5,0,0.0,satisfied
3,25,562,2,5,5,5,2,2,2,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,61,214,3,3,3,3,4,5,5,3,3,4,4,3,3,3,0,0.0,satisfied
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103899,23,192,2,1,2,3,2,2,2,2,3,1,4,2,3,2,3,0.0,neutral or dissatisfied
103900,49,2347,4,4,4,4,2,4,5,5,5,5,5,5,5,4,0,0.0,satisfied
103901,30,1995,1,1,1,3,4,1,5,4,3,2,4,5,5,4,7,14.0,neutral or dissatisfied
103902,22,1000,1,1,1,5,1,1,1,1,4,5,1,5,4,1,0,0.0,neutral or dissatisfied
103903,27,1723,1,3,3,3,1,1,1,1,1,1,4,4,3,1,0,0.0,neutral or dissatisfied

[[0. 1.]
 [0. 1.]
 [1. 0.]
 ...
 [0. 1.]
 [1. 0.]
 [0. 1.]]

In [ ]:
import numpy as np
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

YPandas = aerolines["satisfaction"]     # saca la columna
print(YPandas)
print(YPandas.to_numpy())

Y = le.fit_transform(YPandas.to_numpy())    # lo transforma en 1 y 0
print(Y)

aerolines = aerolines.drop("satisfaction",axis=1)   # quita la Y
X = aerolines.to_numpy()                            # tenemos la X
print(X.shape)

X = np.hstack((aerolines,GenderOHE,CustomerTypeOHE,TypeofTraveOHE,ClassOHE))    # le ponemos las columnas que habiamos hecho ONE HOT ENCODING
print(X.shape)

0         neutral or dissatisfied
1         neutral or dissatisfied
2                       satisfied
3         neutral or dissatisfied
4                       satisfied
                   ...
103899    neutral or dissatisfied
103900                  satisfied
103901    neutral or dissatisfied
103902    neutral or dissatisfied
103903    neutral or dissatisfied
Name: satisfaction, Length: 103592, dtype: object
['neutral or dissatisfied' 'neutral or dissatisfied' 'satisfied' ...
 'neutral or dissatisfied' 'neutral or dissatisfied'
 'neutral or dissatisfied']
[0 0 1 ... 0 0 0]
(103592, 18)
(103592, 27)

In [14]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

scaler = StandardScaler()
X = scaler.fit_transform(X)                             # escala todo 
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=0)       # separa en 25 / 75
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(77694, 27)
(77694,)
(25898, 27)
(25898,)

MLP

In [ ]:
# ReLU -> no linear, dos capas de neuronas ocultas(100 y 20), alpha = 0.01 aprende lento, learning_rate_init = velocidad de aprendizaje
model = MLPClassifier(activation='relu',hidden_layer_sizes=(100,20), max_iter=7000, alpha=0.01, learning_rate_init=0.01, random_state=0)
model.fit(X_train, y_train)
# Obtener las predicciones del clasificador de scikit-learn
y_pred_sklearn = model.predict(X_test)

ac = accuracy_score(y_pred_sklearn,y_test)
print("Accuracy",ac)

Accuracy 0.9628156614410379

RANDOM FOREST

In [ ]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=1000,max_depth=20, random_state=0)
clf.fit(X_train, y_train)
y_predictRF = clf.predict(X_test)

rf_accuracy = accuracy_score(y_test, y_predictRF)
print("accuracy",rf_accuracy)

accuracy 0.9617344968723454

In [ ]:

# Por defecto tiene criterian = "gini" , siendo gini = 0 que estás 100% clasificado y 0.5 mitad y mitad
#criterion = "entropy" usa la formula de los logaritmos esta, es más lenta
clf = RandomForestClassifier(criterion="entropy", n_estimators=1000,max_depth=20, random_state=0)
clf.fit(X_train, y_train)
y_predictRF = clf.predict(X_test)

rf_accuracy = accuracy_score(y_test, y_predictRF)
print("accuracy",rf_accuracy)

accuracy 0.9623136921770021